//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino_App
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CasinoEntities : DbContext
    {
        public CasinoEntities()
            : base("name=CasinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Игры> Игры { get; set; }
        public virtual DbSet<ИсторияИгр> ИсторияИгр { get; set; }
        public virtual DbSet<Отчеты> Отчеты { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Ставки> Ставки { get; set; }
        public virtual DbSet<Транзакции> Транзакции { get; set; }
    }
}
