//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчеты
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> Winnings { get; set; }
        public Nullable<decimal> Losses { get; set; }
        public Nullable<System.DateTime> GeneratedDate { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
