//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ставки
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> CoefficientAtBet { get; set; }
        public Nullable<decimal> Winnings { get; set; }
        public System.DateTime BetTime { get; set; }
    
        public virtual Игры Игры { get; set; }
        public virtual Пользователи Пользователи { get; set; }
    }
}
