//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Casino_App
{
    using System;
    using System.Collections.Generic;
    
    public partial class Транзакции
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
    }
}
